### ISSUE TITLE
Idea for website change

### ISSUE THREAD

**Issue by davidrosenberg** [davidrosenberg/ml2016#16]
So it turns out that the topics list is almost always exactly the same as the anchor text of the slide links.  Seems like we can do away with "topics" entirely, and instead make the first column "SLIDES", the second column "NOTES", and the last column "REFERENCES".  

Might also be nice to shrink the height of a "week" a bit, e.g by not repeating the headers, maybe moving them up to be on same line as "week"?

Thoughts @jandet @domenic  ?

**Comment by domenic** [comment]
> So it turns out that the topics list is almost always exactly the same as the anchor text of the slide links. Seems like we can do away with "topics" entirely, and instead make the first column "SLIDES", the second column "NOTES", and the last column "REFERENCES".

I'm not quite sure what you're envisioning by splitting SLIDES and NOTES? I can understand the idea of collapsing column 2 (topics) and column 4 (slides and notes); that's pretty easy.

To allow this to work we'll need a data file format change. Probably best to work on that in ml2017 once it's set up. Here is the new format I am thinking:

```yaml
  Title: Week 1
  Events:
    2016-01-27:
      Label: Lecture
      Video: "https://youtu.be/U6M0m9c9_Js"
      References:
        - {KPM Ch 1: "http://www.cs.ubc.ca/~murphyk/MLbook/pml-intro-22may12.pdf"}
        - {Bottou's SGD Tricks: "http://leon.bottou.org/papers/bottou-tricks-2012"}
        - BV Preface, Ch 1
      Slides and Notes:
        - {Course Logistics: "https://davidrosenberg.github.io/mlcourse/Archive/2016/Lectures/1a.course-logistics.pdf"}
        - {Statistical Learning Theory: "https://davidrosenberg.github.io/mlcourse/Archive/2016/Lectures/1b.intro-slt-riskdecomp.pdf"}
        - {Stochastic Gradient Descent: "https://davidrosenberg.github.io/mlcourse/Archive/2016/Lectures/1c.stoch-grad-descent.pdf"}
    2016-01-28:
      Label: Lab
      Video: "https://www.youtube.com/watch?v=MEZiIfeqNNI"
      References:
        - {Barnes's "Matrix Differentiation" notes: "http://www.atmos.washington.edu/~dennis/MatrixCalculus.pdf"}
        - {Felippa's "Matrix Calculus" chapter: "http://www.colorado.edu/engineering/cas/courses.d/IFEM.d/IFEM.AppC.d/IFEM.AppC.pdf"}
      Slides and Notes:
        - {Levent's Differentiation Slides: "https://davidrosenberg.github.io/mlcourse/Archive/2016/Labs/1differentiation.pdf"}
        - {Matrix Differentiation: "https://davidrosenberg.github.io/ml2015/docs/matrix-differentiation.pdf"}
        - {Directional Derivatives and Approximation: "https://davidrosenberg.github.io/mlcourse/Archive/2016/Notes/directional-derivative.pdf"}
```

I can't figure out what the difference between "References (supplemental)" and "References (pre)" was supposed to be...

> Might also be nice to shrink the height of a "week" a bit, e.g by not repeating the headers, maybe moving them up to be on same line as "week"?

That makes sense to me!
